name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header
          config_timezone: America/Los_Angeles
          debug_print: yes
          plugin_achievements: yes
          plugin_activity: yes
          plugin_gists: yes
          plugin_projects: yes
          plugin_introduction: yes
          plugin_languages: yes
          template: classic
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
